/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const ReservationIndexLazyImport = createFileRoute('/reservation/')()
const TripsPageLazyImport = createFileRoute('/trips/page')()
const ReservationSuccessLazyImport = createFileRoute('/reservation/success')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ReservationIndexLazyRoute = ReservationIndexLazyImport.update({
  path: '/reservation/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/reservation/index.lazy').then((d) => d.Route),
)

const TripsPageLazyRoute = TripsPageLazyImport.update({
  path: '/trips/page',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/trips/page.lazy').then((d) => d.Route))

const ReservationSuccessLazyRoute = ReservationSuccessLazyImport.update({
  path: '/reservation/success',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/reservation/success.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/reservation/success': {
      preLoaderRoute: typeof ReservationSuccessLazyImport
      parentRoute: typeof rootRoute
    }
    '/trips/page': {
      preLoaderRoute: typeof TripsPageLazyImport
      parentRoute: typeof rootRoute
    }
    '/reservation/': {
      preLoaderRoute: typeof ReservationIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  ReservationSuccessLazyRoute,
  TripsPageLazyRoute,
  ReservationIndexLazyRoute,
])

/* prettier-ignore-end */
